global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'user-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['user-service:8081']
        labels:
          application: 'user-service'

  - job_name: 'product-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['product-service:8082']
        labels:
          application: 'product-service'

  - job_name: 'cart-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['cart-service:8083']
        labels:
          application: 'cart-service'
  - job_name: 'order-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['order-service:8084']
        labels:
          application: 'order-service'

  - job_name: 'payment-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['payment-service:8085']
        labels:
          application: 'payment-service'